# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-10-21 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0002_auto_20211021_1033'),
    ]

    operations = [
        migrations.CreateModel(
            name='checkBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='skills',
        ),
    ]
