# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-10-25 15:52
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0003_auto_20211022_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='courses',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Python', 'Python'), ('javascript', 'javascript'), ('React', 'React'), ('MySQL', 'MySQL')], default='courses', max_length=200),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='description',
            field=models.TextField(blank=True, default='Profile Statement', max_length=500),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='phone',
            field=models.CharField(blank=True, default='+46 000 000 0000', max_length=200),
        ),
    ]
