# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-10-25 08:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0003_auto_20211022_1058'),
        ('basic_app', '0003_auto_20211021_1533'),
    ]

    operations = [
    ]
