# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-10-25 08:42
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0004_merge_20211025_1012'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckboxChoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', multiselectfield.db.fields.MultiSelectField(choices=[('Lord of the Ukasha', 'Lord of the Ukasha'), ('Venkatesans adventures in Stockholm', 'Venkatesans adventures in Stockholm'), ('Christoffer tales from KTH', 'Christoffer tales from KTH'), ('Marry the queen of Cebu', 'Marry the queen of Cebu')], max_length=105)),
            ],
        ),
        migrations.DeleteModel(
            name='checkBox',
        ),
    ]
