# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-10-26 14:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0004_auto_20211025_1000'),
        ('basic_app', '0005_contact'),
    ]

    operations = [
    ]
