# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-10-26 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0006_merge_20211026_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='profile_pic',
            field=models.ImageField(blank=True, default='harry.jpeg', upload_to='profile_pics'),
        ),
    ]
