# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-10-27 05:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0007_auto_20211026_2122'),
        ('basic_app', '0006_joblistnews'),
    ]

    operations = [
    ]
