# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-10-25 21:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        #('basic_app', '0008_auto_20211025_1344'),
        ('basic_app', '0004_auto_20211025_1000'),
    ]

    operations = [
    ]
