# Generated by Django 3.2.8 on 2021-10-26 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0005_contact'),
        ('basic_app', '0008_auto_20211025_1344'),
    ]

    operations = [
    ]
