# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-10-25 21:38
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0009_merge_20211025_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='courses',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Python', 'Python'), ('javascript', 'javascript'), ('React', 'React'), ('MySQL', 'MySQL')], default='courses', max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
    ]
