# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-10-26 08:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0005_contact'),
        ('basic_app', '0010_auto_20211025_2138'),
    ]

    operations = [
    ]
